### ISSUE TITLE
Contribution to this project

### ISSUE THREAD

**Issue by James-Kwao** [Laiba-Saeedd/Java-Development#1]
Hi @Laiba-Saeedd, I will like to contribute to this project to better my java dev skill and also get use to open source contribution.

**Comment by Laiba-Saeedd** [comment]
Thank you for forking my repository James-Kwao! I'm glad you found it useful. Feel free to reach out if you have any questions or need assistance with anything.

**Comment by James-Kwao** [comment]
Thanks for reaching out. 😊
